#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OCCT Face Separator - Face Analysis Tool
OCCT 面分离器 - 面分析工具

这个脚本分析由OCCT面分离器生成的BREP文件
This script analyzes BREP files generated by OCCT Face Separator
"""

import os
import glob
import argparse
from typing import List, Tuple

def analyze_brep_files(pattern: str = "*.brep") -> List[Tuple[str, int]]:
    """
    分析BREP文件
    Analyze BREP files
    
    Args:
        pattern: 文件匹配模式 / File pattern to match
        
    Returns:
        List of (filename, file_size) tuples
    """
    brep_files = glob.glob(pattern)
    brep_files.sort()
    
    results = []
    for filename in brep_files:
        if os.path.isfile(filename):
            file_size = os.path.getsize(filename)
            results.append((filename, file_size))
    
    return results

def print_analysis_report(files: List[Tuple[str, int]]):
    """
    打印分析报告
    Print analysis report
    """
    if not files:
        print("没有找到BREP文件 / No BREP files found")
        return
    
    print("=" * 60)
    print("BREP 文件分析报告 / BREP File Analysis Report")
    print("=" * 60)
    
    # 按类型分组文件
    # Group files by type
    box_faces = [f for f in files if 'box_face_' in f[0]]
    cylinder_faces = [f for f in files if 'cylinder_face_' in f[0]]
    sphere_faces = [f for f in files if 'sphere_face_' in f[0]]
    other_faces = [f for f in files if not any(prefix in f[0] for prefix in ['box_face_', 'cylinder_face_', 'sphere_face_'])]
    
    def print_group_info(group_name: str, files_group: List[Tuple[str, int]]):
        if files_group:
            print(f"\n{group_name}:")
            print(f"{'文件名':<25} {'大小(字节)':<12} {'大小(KB)':<10}")
            print(f"{'Filename':<25} {'Size(bytes)':<12} {'Size(KB)':<10}")
            print("-" * 50)
            
            total_size = 0
            for filename, size in files_group:
                total_size += size
                size_kb = size / 1024
                print(f"{filename:<25} {size:<12} {size_kb:<10.2f}")
            
            print("-" * 50)
            print(f"{'总计 / Total:':<25} {total_size:<12} {total_size/1024:<10.2f}")
            print(f"文件数量 / File count: {len(files_group)}")
    
    # 打印各组信息
    # Print group information
    print_group_info("长方体面文件 / Box Face Files", box_faces)
    print_group_info("圆柱体面文件 / Cylinder Face Files", cylinder_faces)
    print_group_info("球体面文件 / Sphere Face Files", sphere_faces)
    print_group_info("其他面文件 / Other Face Files", other_faces)
    
    # 总体统计
    # Overall statistics
    total_files = len(files)
    total_size = sum(size for _, size in files)
    avg_size = total_size / total_files if total_files > 0 else 0
    
    print("\n" + "=" * 60)
    print("总体统计 / Overall Statistics")
    print("=" * 60)
    print(f"总文件数 / Total files: {total_files}")
    print(f"总大小 / Total size: {total_size} 字节 / bytes ({total_size/1024:.2f} KB)")
    print(f"平均大小 / Average size: {avg_size:.2f} 字节 / bytes ({avg_size/1024:.2f} KB)")
    
    # 大小分布
    # Size distribution
    if total_files > 0:
        sizes = [size for _, size in files]
        min_size = min(sizes)
        max_size = max(sizes)
        
        print(f"最小文件 / Smallest file: {min_size} 字节 / bytes ({min_size/1024:.2f} KB)")
        print(f"最大文件 / Largest file: {max_size} 字节 / bytes ({max_size/1024:.2f} KB)")

def check_face_file_integrity(filename: str) -> bool:
    """
    检查面文件的完整性
    Check the integrity of a face file
    """
    try:
        with open(filename, 'r') as f:
            content = f.read()
            # 基本的BREP文件检查
            # Basic BREP file checks
            if not content.strip():
                return False
            # 检查是否包含BREP格式的关键词
            # Check for BREP format keywords
            brep_keywords = ['CASCADE', 'BREP', 'TopoDS', 'FACE']
            return any(keyword in content for keyword in brep_keywords)
    except Exception:
        return False

def validate_brep_files(files: List[Tuple[str, int]]) -> Tuple[List[str], List[str]]:
    """
    验证BREP文件
    Validate BREP files
    
    Returns:
        Tuple of (valid_files, invalid_files)
    """
    valid_files = []
    invalid_files = []
    
    for filename, _ in files:
        if check_face_file_integrity(filename):
            valid_files.append(filename)
        else:
            invalid_files.append(filename)
    
    return valid_files, invalid_files

def cleanup_brep_files(pattern: str = "*.brep", confirm: bool = True) -> int:
    """
    清理BREP文件
    Clean up BREP files
    
    Returns:
        Number of files deleted
    """
    files = glob.glob(pattern)
    
    if not files:
        print("没有找到要删除的BREP文件 / No BREP files found to delete")
        return 0
    
    if confirm:
        print(f"找到 {len(files)} 个BREP文件:")
        print(f"Found {len(files)} BREP files:")
        for f in files:
            print(f"  - {f}")
        
        response = input("\n确定要删除这些文件吗? (y/N) / Are you sure you want to delete these files? (y/N): ")
        if response.lower() not in ['y', 'yes', '是']:
            print("操作已取消 / Operation cancelled")
            return 0
    
    deleted_count = 0
    for filename in files:
        try:
            os.remove(filename)
            deleted_count += 1
            print(f"已删除 / Deleted: {filename}")
        except Exception as e:
            print(f"删除失败 / Failed to delete {filename}: {e}")
    
    print(f"\n总共删除了 {deleted_count} 个文件 / Total {deleted_count} files deleted")
    return deleted_count

def main():
    parser = argparse.ArgumentParser(
        description="OCCT Face Separator - Face Analysis Tool\nOCCT 面分离器 - 面分析工具",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--pattern', '-p',
        default='*.brep',
        help='文件匹配模式 / File pattern to match (default: *.brep)'
    )
    
    parser.add_argument(
        '--validate', '-v',
        action='store_true',
        help='验证BREP文件完整性 / Validate BREP file integrity'
    )
    
    parser.add_argument(
        '--cleanup', '-c',
        action='store_true',
        help='清理BREP文件 / Clean up BREP files'
    )
    
    parser.add_argument(
        '--force', '-f',
        action='store_true',
        help='强制清理，不需要确认 / Force cleanup without confirmation'
    )
    
    args = parser.parse_args()
    
    if args.cleanup:
        cleanup_brep_files(args.pattern, not args.force)
        return
    
    # 分析文件
    # Analyze files
    files = analyze_brep_files(args.pattern)
    print_analysis_report(files)
    
    # 验证文件
    # Validate files
    if args.validate and files:
        print("\n" + "=" * 60)
        print("文件完整性验证 / File Integrity Validation")
        print("=" * 60)
        
        valid_files, invalid_files = validate_brep_files(files)
        
        print(f"有效文件 / Valid files: {len(valid_files)}")
        for f in valid_files:
            print(f"  ✓ {f}")
        
        if invalid_files:
            print(f"\n无效文件 / Invalid files: {len(invalid_files)}")
            for f in invalid_files:
                print(f"  ✗ {f}")
        else:
            print("\n所有文件都是有效的! / All files are valid!")

if __name__ == '__main__':
    main()